version: "3"

services:
  db:
    image: jelenko10/db_image
    build:
      context: ./database
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: docker_books

  backend:
    image: jelenko10/backend_image
    build:
      context: ./backend
    ports:
      - "3000:3000"
    depends_on:
      - db
